### ISSUE TITLE
How to get 4k resolution?

### ISSUE THREAD

**Issue by hopoffbaby** [CryptoCTB/LiberatingMarsCLI#1]
Hi,

@PaulGameDev 

Thanks for this app. I have managed to convert the ctb files produced by Lychee to the encrypted ctb files, and confirmed them in UVTools.

In Lychee, there is no support for Mars3, and therefore no printer profiles with the correct dimensions and 4k screen. When I use the Mars 2 profile the output after conversion when viewing with UVTools is 2k, not the 4k that the Mars 3 can do:

For example UVTools shows the pixel size as 35um for a file created in chitubox, and 51um for a file created in lychee and then converted using liberatingmars.

Do you know how I can get the higher resolution output from Lychee or as part of the conversion?

Thanks

**Comment by PaulGD03** [comment]
Lychee will soon release the necessary profiles needed for proper use with LiberatingMars as far as I'm aware ^^

**Comment by PaulGD03** [comment]
Pinned and kept open until Lychee supports the new resolutions! ^^

**Comment by PaulGD03** [comment]
Closed. Lychee has officially added support for the CTBv4E format in the 3.6 update.
